name: contract-ci

on:
  pull_request:
  push:
    tags:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: docker build -f docker/ci-dockerfile -t juno_local_ci ./setup_and_run.sh juno16g2rahf5846rxzp3fwlswy08fz8ccuwk03k57y
      - name: Docker run
        run: docker run --rm -d --name juno_node_1 -p 1317:1317 -p 26656:26656 -p 26657:26657 ghcr.io/cosmoscontracts/juno:juno_local_ci ./run_junod.sh
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'envoylabs/whoami'
          ref: 'v0.4.1'
      - name: Run deploy script
        run: |
          chmod a+x ./scripts/deploy_ci.sh
          ./scripts/deploy_ci.sh juno16g2rahf5846rxzp3fwlswy08fz8ccuwk03k57y

